# Generated by Django 2.1 on 2018-08-30 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atletas',
            fields=[
                ('idAtleta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('enderecoCep', models.CharField(max_length=9)),
                ('enderecoRua', models.CharField(max_length=50)),
                ('enderecoNum', models.IntegerField(default=0)),
                ('enderecoBairro', models.CharField(max_length=50)),
                ('dataNascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto', models.ImageField(upload_to='')),
                ('dataEntrada', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('dataInativacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Atletas_Posicao',
            fields=[
                ('idAtletaPosicao', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('idPosicao', models.AutoField(primary_key=True, serialize=False)),
                ('idTipoPosicao', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('idSkill', models.AutoField(primary_key=True, serialize=False)),
                ('quarentaJardas', models.DecimalField(decimal_places=3, max_digits=5)),
                ('supino', models.IntegerField(default=0)),
                ('saltoVertical', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saltoHorizontal', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('telefone', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=12)),
                ('recado', models.CharField(max_length=12)),
                ('idAtleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='draft.Atletas')),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='idAtleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Atletas'),
        ),
        migrations.AddField(
            model_name='atletas_posicao',
            name='idAtleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Atletas'),
        ),
        migrations.AddField(
            model_name='atletas_posicao',
            name='idPosicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Posicao'),
        ),
    ]
