# Generated by Django 2.1 on 2018-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='dataInativacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
