# Generated by Django 2.1 on 2018-09-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20180901_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAtletas',
            fields=[
                ('idAtleta', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=10)),
                ('posicao', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='atletas',
            name='tipo',
            field=models.CharField(choices=[(1, 'ATLETA'), (2, 'CANDIDATO')], default='01/01/2000', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atletas',
            name='enderecoBairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='enderecoCep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='enderecoNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='enderecoRua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
