# Generated by Django 2.1 on 2018-09-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20180924_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='dataEntrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
