# Generated by Django 2.1 on 2018-09-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20180926_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletas',
            name='email',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
