# Generated by Django 2.1 on 2018-09-30 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_atletas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='dataEntrada',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
