# Generated by Django 2.1 on 2018-09-30 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20180930_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='dataEntrada',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
