# Generated by Django 2.1 on 2018-10-01 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_auto_20180930_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='dataAvaliacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
