# Generated by Django 2.1 on 2018-10-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletas',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='atletas',
            name='tipo',
            field=models.CharField(blank=True, choices=[(1, 'ATLETA'), (2, 'CANDIDATO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='recado',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
